on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
      - name: List files
        run: ls -la
